### ISSUE TITLE
Vis frem en farge palett fra https://www.paletton.com/ som kan passe til nettsiden

### ISSUE THREAD

**Issue by Trivinyx** [Trivinyx/Gruppe-12A#13]
lek deg på https://www.paletton.com/ og lim inn her palleter du kan teke passer til nettsiden vår, når vi har fått inn noen forslag. Så går vi igjennom de og bestemmer oss for en som vi implementerer.

**Comment by Trivinyx** [comment]
flytt til in progress på kanban bordet når første palett er lagdt inn.

**Comment by Trivinyx** [comment]
![image](https://user-images.githubusercontent.com/89245165/133425633-ef78eb6d-282a-4780-94e9-c346b90f7e65.png)
.color-primary-0 { color: #22B7BE }	/* Main Primary color */
.color-primary-1 { color: #70D7DC }
.color-primary-2 { color: #44C6CC }
.color-primary-3 { color: #01ABB3 }
.color-primary-4 { color: #017B81 }

**Comment by Cathrinerh** [comment]
.color-primary-0 { color: #296480 }	/* Main Primary color */
.color-primary-1 { color: #6B9AB1 }
.color-primary-2 { color: #427893 }
.color-primary-3 { color: #17506B }
.color-primary-4 { color: #073A53 }
<img width="585" alt="farger" src="https://user-images.githubusercontent.com/89384505/133425709-2a725680-dad4-4378-8ffb-04e80dccc0ed.png">

**Comment by Cathrinerh** [comment]
<img width="585" alt="farger" src="https://user-images.githubusercontent.com/89384505/133426048-79508452-8ef4-4392-8353-383a0bb62665.png">
.color-primary-0 { color: #296480 }	/* Main Primary color */
.color-primary-1 { color: #6B9AB1 }
.color-primary-2 { color: #427893 }
.color-primary-3 { color: #17506B }
.color-primary-4 { color: #073A53 }

**Comment by Cathrinerh** [comment]
.color-primary-0 { color: #296480 }	/* Main Primary color */
.color-primary-1 { color: #6B9AB1 }
.color-primary-2 { color: #427893 }
.color-primary-3 { color: #17506B }
.color-primary-4 { color: #073A53 }
<img width="585" alt="farger" src="https://user-images.githubusercontent.com/89384505/133426122-1d3144fd-033b-405a-a2fc-5f43632ef6bf.png">

**Comment by sunnivalien** [comment]
![Skjermbilde 2021-09-15 kl  13 36 26](https://user-images.githubusercontent.com/89248508/133427083-93a9e7a9-5bcc-4b00-a5af-7e6250618f12.png)

.color-primary-0 { color: #3A528E }	/* Main Primary color */
.color-primary-1 { color: #8597C5 }
.color-primary-2 { color: #576DA4 }
.color-primary-3 { color: #243C79 }
.color-primary-4 { color: #122860 }

**Comment by GreaToms** [comment]
![image](https://user-images.githubusercontent.com/89194269/133428159-38e17ce6-80e5-441b-b84d-1cef6fb7a86b.png)

.color-primary-0 { color: #296593 }	/* Main Primary color */
.color-primary-1 { color: #718EA4 }
.color-primary-2 { color: #496D89 }
.color-primary-3 { color: #123652 }
.color-primary-4 { color: #042037 }

**Comment by kitzch** [comment]
![palettforslag](https://user-images.githubusercontent.com/89386903/133631538-87b6fb7d-b697-4f80-b96c-5325a570c82d.JPG)

**Comment by Trivinyx** [comment]
@Karstad mangler et forslag fra deg, før vi begynner og diskutere hvilken palett en skal ha på siden.

**Comment by Karstad** [comment]
![Skjermbilde 2021-09-20 13 57 37](https://user-images.githubusercontent.com/89392091/133998479-823bedac-af95-4849-8844-7c7d2d7f41c6.png)

/* As hex codes */

.color-primary-0 { color: #043374 }	/* Main Primary color */
.color-primary-1 { color: #0C51B1 }
.color-primary-2 { color: #073F8D }
.color-primary-3 { color: #02275B }
.color-primary-4 { color: #01193B }

**Comment by Trivinyx** [comment]
Min Prefererte Fargeliste:

1. @GreaToms 
2. @Cathrinerh 
3. @Karstad 
4. @sunnivalien 
5. @kitzch 
6. @Trivinyx

**Comment by sunnivalien** [comment]
1. @Karstad 
2. @Cathrinerh 
3. @GreaToms 
4. @sunnivalien 
5. @kitzch 
6. @Trivinyx

**Comment by kitzch** [comment]
1. @kitzch 
2. @Trivinyx 
3. @Cathrinerh @GreaToms 
4. @sunnivalien 
5. @Karstad

**Comment by Karstad** [comment]
1. @Karstad  
2. @Trivinyx  
3. @sunnivalien 
4. @GreaToms 
5. @Cathrinerh 
6. @kitzch

**Comment by Cathrinerh** [comment]
1. @GreaToms 
2. @sunnivalien 
3. @Karstad 
4. @Trivinyx 
5. @Cathrinerh
6. @kitzch
