### ISSUE TITLE
Legge inn fargepalett som er valgt.

### ISSUE THREAD

**Issue by Trivinyx** [Trivinyx/Gruppe-12A#14]
farger bestemt i #13

**Comment by sunnivalien** [comment]
![Skjermbilde 2021-09-15 kl  13 36 26](https://user-images.githubusercontent.com/89248508/133426900-86ad0145-3ae9-49a2-a84a-9f08dbdecb66.png)

.color-primary-0 { color: #3A528E }	/* Main Primary color */
.color-primary-1 { color: #8597C5 }
.color-primary-2 { color: #576DA4 }
.color-primary-3 { color: #243C79 }
.color-primary-4 { color: #122860 }

**Comment by Karstad** [comment]
![Skjermbilde 2021-09-20 13 57 37](https://user-images.githubusercontent.com/89392091/133998365-daa89e69-dc43-457c-944a-839f335cf32e.png)

/* As hex codes */

.color-primary-0 { color: #043374 }	/* Main Primary color */
.color-primary-1 { color: #0C51B1 }
.color-primary-2 { color: #073F8D }
.color-primary-3 { color: #02275B }
.color-primary-4 { color: #01193B }

**Comment by Cathrinerh** [comment]
.color-primary-0 { color: #296593
![133428159-38e17ce6-80e5-441b-b84d-1cef6fb7a86b](https://user-images.githubusercontent.com/89384505/134514101-61b22ae9-c798-4c50-9095-52b663b87de9.png)
 } /* Main Primary color */
.color-primary-1 { color: #718EA4 }
.color-primary-2 { color: #496D89 }
.color-primary-3 { color: #123652 }
.color-primary-4 { color: #42037 }
