### ISSUE TITLE
Lag en brukersti til "kollektivhjelpen"

### ISSUE THREAD

**Issue by Trivinyx** [Trivinyx/Gruppe-12A#4]
Legg inn forslag, skisser osv.

**Comment by Cathrinerh** [comment]
<img width="454" alt="Ide til visualisering" src="https://user-images.githubusercontent.com/89384505/131329341-ec825819-96e8-4433-aba8-b6903b15c473.png">

**Comment by Karstad** [comment]
![brukerreise](https://user-images.githubusercontent.com/89392091/131329436-3395cd12-0136-474f-ac81-b4ac9eba087e.png)

**Comment by GreaToms** [comment]
![Brukersti](https://user-images.githubusercontent.com/89194269/131329566-86ca6871-9b53-4609-9a66-ecc7c12214cc.png)

**Comment by Trivinyx** [comment]
Test av webhook
